* 클로저내에서는, (변수 선언을 하는 곳이 따로 없고) 외부 변수를 사용하기 위해, 캡처
* 여기서는 self에 대해 강한 참조를 하게되고 객체에 대한 RC가 +1이 발생하도록 함

* 강한 참조 해결: 캡처리스트 + weak / unowned 사용 클로저 캡처리스트를 사용해서, 강한 참조를 피하는 것 가능 
* 캡처리스트 내에서 weak / unowned를 사용해 참조를 하면, 객체에 대한 RC가 증가하지 않음

# 에러 처리

iOS에서의 에러
1. 컴파일 에러
2. 런타임 에러

```swift
func doSomething(num: Int) throws -> Bool {
    if num >= 7 {
        return true
    } else {
        if num < 0 {
            throw Error
        }
        return false
    }
}
```

에러 처리를 위해서는 함수 리턴 -> 앞에 `throws` 키워드 사용
throws 가 되는 함수는 try 를 사용해서 호출해야함

try를 호출하려면 do catch를 써야하고 안쓰러면 try? 혹은 try!로 호출

에러는 Error 프로토콜을 채택한 열거형으로 만들 수 있음
